Third lab
gorobot-nz/calendarproj pull request #2
Opened 2022-03-06 17:51 UTC by gorobot-nz

Link - `https://gorobot-nz.github.io/calendarproj/project/index.html`

2022-03-09 11:42 UTC, katetushkan requested changes

2022-03-09 11:42 UTC, katetushkan commented on project/styles.css
> +header {
use styles

2022-03-09 11:42 UTC, katetushkan commented on project/styles.css
> +    background-color: lightsteelblue;
put ur coolers in css var, will be easier to change them.

2022-03-09 11:42 UTC, katetushkan commented on project/styles.css
> +    height: 10vh;
don't use vh, it can be tricky with Mobile layouts, also do not specify sizes of the containers, it should be scalable depending on the content inside

2022-03-09 11:42 UTC, katetushkan commented on project/styles.css
> +    top: 1.5px;
don't use half a px, browser can make a mistake during counting and painting. also it's better to use rem, read about it pls

2022-03-09 11:42 UTC, katetushkan commented on project/styles.css
> +}
Everything is almost fine. pls, check the comments, 

center icons
<img width="174" alt="Screenshot 2022-03-09 at 12 41 07" src="https://user-images.githubusercontent.com/43992068/157435008-fbeb9806-89d5-46b3-9bd4-f57412e70589.png">

and add more spaces around text, it will look nicer
<img width="94" alt="Screenshot 2022-03-09 at 12 41 25" src="https://user-images.githubusercontent.com/43992068/157435038-686e0e51-384e-4ecb-a77d-d07040e4ac29.png">

Good job!

2022-03-09 11:44 UTC, katetushkan requested changes

2022-03-09 11:44 UTC, katetushkan commented on project/styles.css
> +.button-content {
for buttons, add hover, focus, active and disabled styles

2022-03-09 12:05 UTC, gorobot-nz commented on project/styles.css
> +header {
Waht does it mean 'use styles?'? Add className for header tag?

2022-03-09 17:50 UTC, gorobot-nz commented on project/styles.css
> +    height: 10vh;
I prefer not to use vh and not to specify containers' sizes, but when i am trying to set % scales to header and main tags, my page looks sick
![screen](https://user-images.githubusercontent.com/61064343/157501101-ec86d646-f2d4-49e9-b8de-e7e3e0c492c9.png)

2022-03-10 07:31 UTC, katetushkan commented on project/styles.css
> +header {
yes, correct

2022-03-10 07:40 UTC, katetushkan commented on project/styles.css
> +    height: 10vh;
don't specify height for a header at all, but ad correct margins to ur container' items and set proper justify and specify properties. Actually u don't need here additional "container" layer just put ur buttons inside header

I switched off "height" property here. It looks okay
<img width="832" alt="Screenshot 2022-03-10 at 08 39 13" src="https://user-images.githubusercontent.com/43992068/157612137-2e4834d4-cf28-4317-932a-66098a4d842d.png">
.

2022-03-10 07:51 UTC, katetushkan commented
<img width="205" alt="Screenshot 2022-03-10 at 08 50 01" src="https://user-images.githubusercontent.com/43992068/157613778-97f64158-b9a7-4317-8494-fa99cee32b7f.png">

Are these items gonna be clickable?

2022-03-10 19:18 UTC, gorobot-nz commented
> <img alt="Screenshot 2022-03-10 at 08 50 01" width="205" src="https://user-images.githubusercontent.com/43992068/157613778-97f64158-b9a7-4317-8494-fa99cee32b7f.png">
> 
> Are these items gonna be clickable? If it's an option and then u press "+" button, then it should be radio. But I'd recommend u to get rid of "+" button, and make "task", "event", "reminder" clickable

It's not optional buttons. After click you will see modal and use it to delete or edit event/task/reminder

2022-03-14 10:26 UTC, katetushkan commented
> > <img alt="Screenshot 2022-03-10 at 08 50 01" width="205" src="https://user-images.githubusercontent.com/43992068/157613778-97f64158-b9a7-4317-8494-fa99cee32b7f.png">
> > Are these items gonna be clickable? If it's an option and then u press "+" button, then it should be radio. But I'd recommend u to get rid of "+" button, and make "task", "event", "reminder" clickable
> 
> It's not optional buttons. After click you will see modal and use it to delete or edit event/task/reminder

Okay, than it should be <button/>, not <div/>, without <div/> inside, u just do <button>Tasks</button>

If u okay with that, I'll give u 10 and u will change it in ur next work.

2022-03-14 10:32 UTC, gorobot-nz commented
> 
Ok. Approve the merge commit and I'll move on to the next lab

2022-03-14 10:33 UTC, gorobot-nz commented
> > > <img alt="Screenshot 2022-03-10 at 08 50 01" width="205" src="https://user-images.githubusercontent.com/43992068/157613778-97f64158-b9a7-4317-8494-fa99cee32b7f.png">
> > > Are these items gonna be clickable? If it's an option and then u press "+" button, then it should be radio. But I'd recommend u to get rid of "+" button, and make "task", "event", "reminder" clickable
> > 
> > 
> > It's not optional buttons. After click you will see modal and use it to delete or edit event/task/reminder
> 
> Okay, than it should be , not
> 
> , without
> inside, u just do
> Tasks
> If u okay with that, I'll give u 10 and u will change it in ur next work.

Ok. Approve the merge commit and I'll move on to the next lab

2022-03-14 10:35 UTC, katetushkan approved these changes
10.

2022-03-14 10:56 UTC, merged